<?php
/*
 *  mars
 *  https://github.com/nizarahmed/mars
 *  PHP Tool to Generate PHP Classes of MySQL Database Tables
 *
 **/

define("DB_NAME", "") ;
define("DB_USER", "") ;
define("DB_PASS", "") ;
define("DB_DOMAIN", "") ;

class Mars {
    
    private $mysql ;
    
    function Mars() {
        $this->db_conn() ;
    }
    
    private function db_conn()
    {
        $this->mysql = new mysqli(DB_DOMAIN, DB_USER, DB_PASS, DB_NAME) ;
        if ($this->mysql->connect_errno) {
                echo "Failed to connect to MySQL: (" . $this->mysql->connect_errno . ") " . $this->mysql->connect_error;
        }
    }
    
    public function generate() {
        
        mkdir("DB") ;
        $tables = $this->execute_query("show tables") ;
        
        foreach($tables as $table_obj) {
            
            $table = $table_obj->{"Tables_in_" . DB_NAME} ;
            $cols = $this->execute_query("describe $table") ;
            $col_names = array() ;
            $pri_key = "" ;

            foreach($cols as $col) {
                $col_name = $col->Field  ;
                $col_type = $col->Type ;
                
                $col_names[] = $col_name ;
                if( $col->Key == "PRI" ) $pri_key = $col_name ;
            }
            
            $emptyValue = '%oi9l^lf>ty' ;
            
            $vars_txt = "" ;
            $update_vals = "" ;
            $update_if = "\t\t\$values = '' ;\n" ;
            $insert_if = "\t\t\$cols = '' ;\n\t\t\$vals = '' ;\n" ;
            $clear_vals = "" ;
            
            foreach($col_names as $col_name) {
                
                $vars_txt .= "\tpublic static \$$col_name = '$emptyValue' ;\n" ;
                
                $insert_if .= "\t\tif( self::\$$col_name != '$emptyValue' || \$force) {\n" ;
                $insert_if .= "\t\t\t\$cols .= \"$col_name,\" ;\n" ;
                $insert_if .= "\t\t\t\$vals .= (self::\$$col_name == '$emptyValue' || self::\$$col_name == null ? \"NULL\" : \"'\". self::\$$col_name .\"'\").\",\" ;\n" ;
                $insert_if .= "\t\t}\n" ;
                
                $clear_vals .= "\t\t\$$col_name = '$emptyValue' ;\n"  ;
                if( $col_name == $pri_key ) continue ;
                
                $update_if .= "\t\tif( self::\$$col_name != '$emptyValue' || \$force) \n" ;
                $update_if .= "\t\t\t\$values .= \"$col_name=\" . (self::\$$col_name == '$emptyValue' || self::\$$col_name == null ? \"NULL\" : \"'\".$table::\$$col_name.\"'\").\",\" ;\n" ;
            }
            
            $fh = fopen("DB/".strtolower("$table.php"), "w") ;
            
            $select_all_txt = "\tpublic static function SelectAll() {\n" ;
            $select_all_txt.= "\t\tself::clearValues() ;\n" ;
            $select_all_txt.= "\t\treturn \"select * from $table\" ;\n" ;
            $select_all_txt.= "\t}\n" ;
            
            $select_where_txt = "\tpublic static function SelectAllWherePriKey(\$val) {\n" ;
            $select_where_txt.= "\t\tself::clearValues() ;\n" ;
            $select_where_txt.= "\t\treturn \"select * from $table where $pri_key='\$val'\" ;\n" ;
            $select_where_txt.= "\t}\n" ;
            
            $delete_txt = "\tpublic static function DeleteWherePriKey(\$val) {\n" ;
            $delete_txt.= "\t\tself::clearValues() ;\n" ;
            $delete_txt.= "\t\treturn \"delete from $table where $pri_key='\$val'\" ;\n" ;
            $delete_txt.= "\t}\n" ;
            
            $update_txt = "\tpublic static function UpdateWherePriKey(\$val, \$force=false) {\n" ;
            $update_txt.= $update_if ;
            $update_txt.= "\t\tself::clearValues() ;\n" ;
            $update_txt.= "\t\treturn \"update $table set \".substr(\$values, 0, strlen(\$values)-1).\" where $pri_key='\$val'\" ;\n" ;
            $update_txt.= "\t}\n" ;
            
            $insert_txt = "\tpublic static function Insert(\$force=false) {\n" ;
            $insert_txt .= $insert_if ;
            $insert_txt.= "\t\tself::clearValues() ;\n" ;
            $insert_txt.= "\t\treturn \"insert into $table (\".substr(\$cols, 0, strlen(\$cols)-1).\") values(\".substr(\$vals, 0, strlen(\$vals)-1).\")\" ;\n" ;
            $insert_txt.= "\t}\n" ;
            
            $clear_txt = "\tprivate static function clearValues() {\n" ;
            $clear_txt.= $clear_vals ;
            $clear_txt.= "\t}\n" ;
            
            $class_txt = "<?php\n" ;
            $class_txt.= "/*\n * Code Generated By mars Copyrights 2014\n * http://github.com/nizarahmed/mars/\n*/\n" ;
            $class_txt.= "class $table {\n$vars_txt\n$select_all_txt\n$select_where_txt\n$delete_txt\n$update_txt\n$insert_txt\n$clear_txt\n}?>" ;
            
            fwrite($fh, $class_txt) ;
            fclose($fh) ;
        }
    }
    
    private function execute_query($q) {
        $res = $this->mysql->query($q) ;
        $rows = array() ;
        while( $row = $res->fetch_object() ) $rows[] = $row ;
        return $rows ;
    }
}

?>